### PR TITLE
build: update ratatui to v0.27

### PR DESCRIPTION
**Pull request by DieracDelta**

### CODE REVIEW

**Comment by EdJoPaTo** [comment]
This could also use the new reexports for crossterm in the examples?

Are there other things from the 0.27 release that improve the tree widget? (Haven’t read the release notes yet)

**Comment by AnthonyMichaelTDM** [comment]
> Are there other things from the 0.27 release that improve the tree widget? (Haven’t read the release notes yet)

Not that I noticed (just gave it a quick once-over)

**Comment by EdJoPaTo** [comment]
> Should be using the crossterm re-export now.

I inlined them back as `crossterm::…` as it seems easier to me to read what is happening there. It's something specific to crossterm. https://github.com/ratatui-org/ratatui/pull/1180 will be way easier to understand once merged.

**Comment by EdJoPaTo** [comment]
Thank you two for looking into the release and updating this library! Its published now as 0.21.0 ✨

**Pull request merged**
